#application: events-concept
#version: master

runtime: python27
api_version: 1
threadsafe: true
resources:
  cpu: 2
  memory_gb: 2

libraries:
- name: MySQLdb
  version: "1.2.5"

handlers:
- url: /api/.*
  script: main.app

- url: /(.*\.(css|js|jpg|png|ico|json|ttf|woff|woff2|map))$
  static_files: dist/\1
  upload: dist/.*\.(css|js|jpg|png|ico|json|ttf|woff|woff2|map)$

- url: /[A-Za-z0-9/-]*
  upload: dist/index.html
  static_files: dist/index.html
