application: concept-event
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: /img
  static_dir: dist/img

- url: /images
  static_dir: dist/images

- url: /css
  static_dir: dist/css

- url: /js
  static_dir: dist/js

- url: /fonts
  static_dir: dist/fonts

- url: /json
  static_dir: dist/json

- url: /[A-Za-z0-9/-]*
  upload: dist/index.html
  static_files: dist/index.html
